### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by dswalter** [benedekrozemberczki/GEMSEC#1]
What is the intended license for this software?

**Comment by benedekrozemberczki** [comment]
It is the reference implementation of a KDD '18 submission. Why?

**Comment by dswalter** [comment]
I work at a corporation, and I am scrupulous about honoring software licenses. I would imagine this is some form of research-acceptable, non-commercial license, but I wasn't able to see what it was.

**Comment by benedekrozemberczki** [comment]
Do You have some specific use-case in mind?
