### ISSUE TITLE
about node id of dataset

### ISSUE THREAD

**Issue by wen-fei** [benedekrozemberczki/GEMSEC#11]
hello, thanks for your great work. I have one question about datasets of your several related code implementations. you said `Nodes should be indexed starting with 0. ` Does this mean that the node code in the dataset is an index after the original node is encoded by its serial number?

**Comment by benedekrozemberczki** [comment]
It should be 0,1,..,N-1.

**Comment by wen-fei** [comment]
Do code ids have to be consecutive?

**Comment by benedekrozemberczki** [comment]
Yes!
