### ISSUE TITLE
How to config Project

### ISSUE THREAD

**Issue by leanhboi1999** [benedekrozemberczki/GEMSEC#12]
I have problem when i run the project.
According to readme.md, I config project at python 3.5, but pip install pandas fail. It has error: Module NotFound "Pandas"
Please let me know the environment to run this project.
We are the student of University of Information Technology - Ho Chi Minh National University. We are researching your paper to do homework of final project.
I hope you reply soon. Thank you for your help.

**Comment by benedekrozemberczki** [comment]
Can you provide more details?

**Comment by benedekrozemberczki** [comment]
I do not know what is your system setup and so on.
